apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow
  namespace: your-namespace
  labels:
    app: mlflow
data:
  MLFLOW_S3_ENDPOINT_URL: ---
  MLFLOW_TRACKING_URI: mlflow-tracking-uri
  AWS_ACCESS_KEY_ID: ---
  AWS_SECRET_ACCESS_KEY: ---
