apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mlflow
  labels:
    app: mlflow
    prometheus: prometheus
spec:
  namespaceSelector:
    matchNames:
      - your-namespace
  selector:
    matchLabels:
      app: mlflow
  endpoints:
    - port: http
      interval: 10s
      path: /metrics
