kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlflow
  namespace: your-namespace
  labels:
    app: mlflow
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
