{{- if .Values.pvc.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{ if .Values.pvc.keep }}
  annotations:
    helm.sh/resource-policy: "keep"
  {{ end }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{- end }}
