apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.mlflow.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.mlflow.aws_secret_access_key }}
